# Generated by Django 2.2 on 2021-01-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='学号/工号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('wechat', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信')),
                ('collage', models.CharField(max_length=20, verbose_name='学院')),
                ('classname', models.CharField(blank=True, max_length=20, null=True, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=20, null=True, verbose_name='专业')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20, verbose_name='性别')),
                ('usertype', models.CharField(choices=[('normal', '学生'), ('admin', '教师')], default='学生', max_length=20, verbose_name='用户类型')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
